name: my_shelf_mysql_app
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
#  mysql1: ^0.20.0
#  mysql_client: ^0.0.27
  dotenv: ^4.2.0
  orm: ^5.3.3
#  shelf_body_parser: ^1.1.2 # To parse JSON or form data from requests
#  mysql1: ^0.20.0 # The MySQL client library
  # Optional for logging
#  shelf_logger: ^1.0.1
  # Optional for environment variables (e.g., database credentials)
#  dotenv: ^2.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
