name: my_shelf_mysql_app
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_multipart: ^2.0.1
  shelf_static: ^1.1.3
  dotenv: ^4.2.0
  orm: ^5.3.3
  mime: ^1.0.6
  path_provider: ^2.1.5

  jaguar_jwt: ^3.0.0
  crypto: ^3.0.6
  bcrypt: ^1.1.3
  uuid: ^4.5.1
#  argon2_ffi_base: ^1.1.1
#  watcher: ^1.1.1
#  shelf_hotreload: ^1.5.0
#  logging: ^1.3.0
#  hotreloader: ^4.3.0
#  shelf_body_parser: ^1.1.2 # To parse JSON or form data from requests
#  mysql1: ^0.20.0 # The MySQL client library
  # Optional for logging
#  shelf_logger: ^1.0.1
  # Optional for environment variables (e.g., database credentials)
#  dotenv: ^2.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
